# Might want to use buildback-deps:bookworm for extra build tools
FROM ghcr.io/astral-sh/uv:python3.12-bookworm

WORKDIR /app

RUN groupadd -r app && \
    useradd -l -r -g app -d /app -c "Docker image user" app && \
    mkdir -p /app && \
    chown -R app:app /app

# Install Node.js LTS for marimo (code completion, formatting, etc.), dumb-init, and locales
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs dumb-init locales && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

USER 999

ENV PATH=/app/.local/bin:/app/.venv/bin:${PATH} PYTHONUNBUFFERED=1 UV_LINK_MODE=copy MARIMO_MANAGE_SCRIPT_METADATA=true PS1="app@marimo:\w$ "

RUN uv venv && \
    uv init && \
    uv add streamlit toml weave packageurl-python

COPY mods /mods
COPY sdk /sdk

EXPOSE 6637

HEALTHCHECK --start-interval=1s --start-period=30s --interval=10s CMD curl -f http://localhost:6638/health

ENTRYPOINT [ "/usr/bin/dumb-init", "--"]

CMD ["python", "/mods/dev-entrypoint.py"]
