FROM denoland/deno:bin-2.3.5 AS bin
# Might want to use buildback-deps:bookworm for extra build tools
FROM ghcr.io/astral-sh/uv:python3.12-bookworm

WORKDIR /app

RUN groupadd -r app && \
    useradd -l -r -g app -d /app -c "Docker image user" app && \
    mkdir -p /app && \
    chown -R app:app /app

USER 999

ENV PATH=/app/.local/bin:/app/.venv/bin:${PATH} PYTHONUNBUFFERED=1 UV_LINK_MODE=copy MARIMO_MANAGE_SCRIPT_METADATA=true

RUN uv venv && \
    uv init && \
    uv add streamlit toml weave packageurl-python && \
    uv tool install dumb-init

COPY mods /mods
COPY sdk /sdk

EXPOSE 6637

COPY --from=bin /deno /usr/bin/deno

ENV DENO_DIR=/app/.deno
ENV DENO_INSTALL_ROOT=/app/.deno
ENV PATH=/app/.deno/bin:${PATH}
RUN mkdir -p /app/.deno/bin

HEALTHCHECK --start-interval=1s --start-period=30s --interval=10s CMD curl -f http://localhost:6638/health

ENTRYPOINT [ "/app/.local/bin/dumb-init", "--"]

CMD ["python", "/mods/dev-entrypoint.py"]
