name: Build mods dev container

permissions:
  contents: read
  id-token: write
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: depot-ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Determine registry
        id: registry
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "image=us-central1-docker.pkg.dev/wandb-production/mods/dev" >> $GITHUB_OUTPUT
            echo "idpool=projects/959666683579/locations/global/workloadIdentityPools/weave-mods-pool/providers/github" >> $GITHUB_OUTPUT
            echo "sa=weave-mods-builder@wandb-production.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
          else
            echo "image=us-central1-docker.pkg.dev/wandb-qa/mods/dev" >> $GITHUB_OUTPUT
            echo "idpool=projects/281760294016/locations/global/workloadIdentityPools/weave-mods-pool/providers/github" >> $GITHUB_OUTPUT
            echo "sa=weave-mods-builder@wandb-qa.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/wandb/weave-mods/dev
            ${{ steps.registry.outputs.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      #- name: QEMU
      #  uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to GCP
        if: ${{ steps.registry.outputs.idpool != '' }}
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ steps.registry.outputs.idpool }}
          service_account: ${{ steps.registry.outputs.sa }}

      - name: Configure Docker for Artifact Registry
        if: ${{ steps.registry.outputs.idpool != '' }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Docker Buildx (Build & Push)
        uses: depot/build-push-action@v1
        with:
          project: f67hp2n7bm
          context: .
          file: Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
